{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-equalityml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/EqualityAI/EqualityML/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54041af706c40ebcc2683c8d423e6abfd362eaf2e695c01a6b293f6277460e2b

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dalex
    - r-fairmodels
  run:
    - r-base
    - r-dalex
    - r-fairmodels

test:
  commands:
    - $R -e "library('equalityml')"           # [not win]

about:
  home: https://equalityai.com
  license: Apache-2.0
  summary: Algorithms for evaluating fairness metrics and mitigating unfairness in supervised machine learning
  license_family: Apache
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach
